### PR TITLE
Different method for retrieving process path.

### PR DESCRIPTION
**Pull request by horsenit**
Previous method occasionally breaks completely (PUBG, process path returned is null)
And will also ocassionally get capitalization wrong, breaking process name matching (could/should make this case insensitive anyways?) (Hitman 2016, should be HITMAN.exe, but returns hitman.exe)

This is on latest Windows 10, by the way.

### CODE REVIEW

**Comment by juvlarN** [comment]
Does vibranceGUI work with PUBG in this commit?

**Comment by juvlarN** [comment]
What about x64 processes? Remember: vibranceGUI is running as a x86 executable, which might cause conflicts.

**Comment by horsenit** [comment]
Yes, this works with PUBG now (it worked before with manually finding the executable, but this allows the process list to work correctly.) PUBG, and Hitman are x64 processes, so it does work correctly with them.

**Comment by juvlarN** [comment]
Good catch, thanks

**Comment by juvlarN** [comment]
Oh it looks like there are some incompatibilities though?
https://technet.microsoft.com/de-de/library/ms683198.aspx (in the comments).

**Comment by horsenit** [comment]
Oh, sorry. Maybe this is something that was changed in later versions of Windows? I don't have anything running an earlier version to readily check.

**Comment by horsenit** [comment]
I believe QueryFullProcessImageName should work for retrieving the process name from x86, however it's only available from Vista onwards if that's a concern.

Sorry about this.

**Comment by juvlarN** [comment]
Can you try if this executable works for you (finding PUBG and other x64 programs?)


[vibrance.GUI.exe.zip](https://github.com/juvlarN/vibranceGUI/files/1185673/vibrance.GUI.exe.zip)

**Comment by horsenit** [comment]
Yes, it does work correctly for me.

**Pull request merged**
